# Generated by Django 3.0.4 on 2020-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operators',
            new_name='Operator',
        ),
    ]
