# Generated by Django 3.0.4 on 2020-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200331_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='opeartor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
